common: &common
  username: bridgeit
  password:
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *common
  database: bridgeit_development
test:
  <<: *common
  database: bridgeit_test
production:
  <<: *common
  database: bridgeit_production
